Arthur kozik hw8
katemalash/Rv-081.PythonCore pull request #51
Opened 2022-03-04 05:25 UTC by ArthurLimenberg

Homework

2022-03-07 12:12 UTC, katemalash approved these changes
Please change the destination branch 
![image](https://user-images.githubusercontent.com/35248902/157032238-3b03547c-cc31-452a-affd-624d5b2c4e2a.png)

2022-03-07 14:03 UTC, katemalash requested changes
Please change the destination branch

2022-03-09 08:35 UTC, ArthurLimenberg commented
Changed

2022-03-11 10:28 UTC, katemalash approved these changes
Good Job. Please merge this pull request.

2022-03-11 10:28 UTC, katemalash commented on Kozik/HW8/Task1.py
> +    result = 'Unknown operation'
It would be nice to have an empty line before 'if' block

2022-03-11 10:28 UTC, katemalash commented on Kozik/HW8/Task3.py
> +from Task5 import is_year_leap
Nice solution

2022-03-11 10:28 UTC, katemalash commented on Kozik/HW8/Task4.py
> +    for divider in range(2, num):
Is it possible to optimize this range?

2022-03-11 13:17 UTC, merged